### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/storytime#4]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md
- [x] diagrams

**Comment by lauraclay** [comment]
Images need to be moved into the images folder and links updated.

**Comment by MissPhilbin** [comment]
I've moved the images into a new folder.
